r305Parser: r305_avr.c File Reference
r305_avr.c File Reference
#include <avr/io.h>
#include <inttypes.h>
#include "r305Parser.h"
Functions
data_package getBasePackage (uint8_t pid, uint16_t length, uint8_t *data)
data_package getDefaultPackage (uint8_t pid)
data_package getAckPackage ()
data_package getCommandPackage (uint16_t length, uint8_t *data)
uint16_t setChecksum (data_package *package)
uint32_t setPackageSize (data_package *package)
uint8_t * stringyfyPackage (data_package *package)
uint8_t loadPackage (uint8_t *package_string, data_package *package)
void sendPackage (data_package *package, void(*Write_fn)(uint8_t *, uint32_t))
int recvPackage (data_package *package, uint16_t size, void(*Read_fn)(uint8_t *, uint32_t))
void UARTInit (uint16_t ubrr_value)
uint8_t UARTReadChar ()
void UARTWriteChar (uint8_t data)
void UARTReadStr (uint8_t *buffer, uint32_t size)
void UARTWriteStr (uint8_t *buffer, uint32_t size)
void main ()
Function Documentation
data_package getAckPackage ()
Definition at line 33 of file r305_avr.c.
data_package getBasePackage (uint8_t pid, uint16_t length, uint8_t * data)
Parameters
pid
length
data
Returns
Definition at line 8 of file r305_avr.c.
Referenced by getCommandPackage().
data_package getCommandPackage (uint16_t length, uint8_t * data)
Definition at line 37 of file r305_avr.c.
Referenced by main().
data_package getDefaultPackage (uint8_t pid)
Parameters
pid
Returns
Definition at line 25 of file r305_avr.c.
Referenced by getAckPackage().
uint8_t loadPackage (uint8_t * package_string, data_package * package)
Definition at line 84 of file r305_avr.c.
Referenced by recvPackage().
void main ()
Definition at line 193 of file r305_avr.c.
References data_package::ack_command_code, ACK_COMMAND_EXEC_COMPLETE, COMMAND_VFY_PWD, getCommandPackage(), LEN_ACK_VFY_PWD, LEN_COMMAND_VFY_PWD, recvPackage(), sendPackage(), UARTReadStr(), and UARTWriteStr().
int recvPackage (data_package * package, uint16_t size, void(*)(uint8_t *, uint32_t) Read_fn)
Definition at line 134 of file r305_avr.c.
Referenced by main().
void sendPackage (data_package * package, void(*)(uint8_t *, uint32_t) Write_fn)
Definition at line 125 of file r305_avr.c.
Referenced by main().
uint16_t setChecksum (data_package * package)
Definition at line 42 of file r305_avr.c.
Referenced by getBasePackage(), loadPackage(), and sendPackage().
uint32_t setPackageSize (data_package * package)
Definition at line 51 of file r305_avr.c.
Referenced by getBasePackage(), loadPackage(), and sendPackage().
uint8_t* stringyfyPackage (data_package * package)
Definition at line 57 of file r305_avr.c.
Referenced by getBasePackage().
void UARTInit (uint16_t ubrr_value)
Definition at line 149 of file r305_avr.c.
uint8_t UARTReadChar ()
Definition at line 166 of file r305_avr.c.
void UARTReadStr (uint8_t * buffer, uint32_t size)
Definition at line 179 of file r305_avr.c.
Referenced by main().
void UARTWriteChar (uint8_t data)
Definition at line 173 of file r305_avr.c.
void UARTWriteStr (uint8_t * buffer, uint32_t size)
Definition at line 186 of file r305_avr.c.
Referenced by main().