r305Parser: r305Parser.c File Reference
r305Parser.c File Reference
Implementation of r305Parser functions.
#include "r305Parser.h"
Functions
data_package getBasePackage (uint8_t pid, uint16_t length, uint8_t *data)
Get default package structure filled with given parameters.
data_package getDefaultPackage (uint8_t pid)
Get empty package with default settings.
data_package getAckPackage ()
Same as getDefaultPackage(ACK_PACKAGE)
data_package getCommandPackage (uint16_t length, uint8_t *data)
Get command package.
uint16_t autoSetChecksum (data_package *package)
Calculates and sets the data_package::checksum bytes in package.
uint32_t autoSetPackageSize (data_package *package)
Calculate and set data_package::package_size parameter.
uint8_t * stringyfyPackage (data_package *package)
Convert data_package structure to byte string and set data_package::package_string parameter.
uint8_t loadPackage (uint8_t *package_string, data_package *package)
Load complete data_package structure from byte string.
void sendPackage (data_package *package, void(*Write_fn)(uint8_t *, uint32_t))
Send data_package using callback function Write_fn.
int recvPackage (data_package *package, uint16_t size, void(*Read_fn)(uint8_t *, uint32_t))
Detailed Description
Implementation of r305Parser functions.
Definition in file r305Parser.c.
Function Documentation
uint16_t autoSetChecksum (data_package * package)
Calculates and sets the data_package::checksum bytes in package.
Parameters
package pointer to a data_package.
Returns
Calculated checksum bytes.
Definition at line 69 of file r305Parser.c.
References data_package::checksum, data_package::data, data_package::length, and data_package::pid.
Referenced by getBasePackage(), loadPackage(), and sendPackage().
uint32_t autoSetPackageSize (data_package * package)
Calculate and set data_package::package_size parameter.
Parameters
package pointer to a data_package.
Returns
Calculated size of package.
Definition at line 83 of file r305Parser.c.
References data_package::address, data_package::header, data_package::length, data_package::package_size, and data_package::pid.
Referenced by getBasePackage(), loadPackage(), and sendPackage().
data_package getAckPackage ()
Same as getDefaultPackage(ACK_PACKAGE)
Returns
package with default settings and empty data.
Definition at line 49 of file r305Parser.c.
References getDefaultPackage().
data_package getBasePackage (uint8_t pid, uint16_t length, uint8_t * data)
Get default package structure filled with given parameters.
Parameters
pid data_package::pid byte to define type of package of the package from PID definitions.
length data_package::length Parameter of package, use Length definitions.
data data_package::data Array of bytes to set as data of the package.
Returns
data_package structure with defaults settings and specified configurations.
Definition at line 15 of file r305Parser.c.
References autoSetChecksum(), autoSetPackageSize(), data_package::length, and stringyfyPackage().
Referenced by getCommandPackage().
data_package getCommandPackage (uint16_t length, uint8_t * data)
Get command package.
Parameters
length data_package::length Parameter of package, use Length definitions.
data data_package::data Array of bytes to set as data of the package.
Returns
command package with default settings and specified configurations.
Definition at line 59 of file r305Parser.c.
References getBasePackage().
data_package getDefaultPackage (uint8_t pid)
Get empty package with default settings.
Parameters
pid data_package::pid byte to define type of package of the package from PID definitions.
Returns
data_package structure with defaults settings
Definition at line 37 of file r305Parser.c.
References data_package::address, DEFAULT_ADDRESS, DEFAULT_HEADER, data_package::header, and data_package::pid.
Referenced by getAckPackage().
uint8_t loadPackage (uint8_t * package_string, data_package * package)
Load complete data_package structure from byte string.
Parameters
package_string Input byte string.
package Pointer to data_package to load.
Returns
-1: if checksum match. -0: if checksum mismatch.
Definition at line 127 of file r305Parser.c.
References data_package::ack_command_code, data_package::address, autoSetChecksum(), autoSetPackageSize(), data_package::checksum, data_package::data, data_package::data_size, data_package::header, data_package::length, data_package::package_size, data_package::package_string, and data_package::pid.
Referenced by recvPackage().
int recvPackage (data_package * package, uint16_t size, void(*)(uint8_t *, uint32_t) Read_fn)
Parameters
package data_package to load received data.
size No. of bytes to receive. For most of ACK package use LEN_ACK* + 9.
Read_fn callback function to read data bytes.
Returns
1: for valid package. 0: for invalid package.
See also
LengthACK
Definition at line 199 of file r305Parser.c.
References loadPackage().
void sendPackage (data_package * package, void(*)(uint8_t *, uint32_t) Write_fn)
Send data_package using callback function Write_fn.
Parameters
package data_package to be sent.
Write_fn callback function
Definition at line 180 of file r305Parser.c.
References autoSetChecksum(), autoSetPackageSize(), data_package::package_size, and data_package::package_string.
uint8_t* stringyfyPackage (data_package * package)
Convert data_package structure to byte string and set data_package::package_string parameter.
Parameters
package pointer to a data_package.
Returns
byte string of input data_package.
Definition at line 94 of file r305Parser.c.
References data_package::address, data_package::checksum, data_package::data, data_package::data_size, data_package::header, data_package::length, data_package::package_string, and data_package::pid.
Referenced by getBasePackage().