r305Parser: test.c File Reference
test.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "r305Parser.h"
Functions
void printFn (uint8_t *str, uint32_t size)
void scanFn (uint8_t *str, uint32_t size)
int main (int argc, char const *argv[])
Variables
data_package txPackage
Function Documentation
int main (int argc, char const * argv[])
Definition at line 21 of file test.c.
References COMMAND_VFY_PWD, getCommandPackage(), LEN_COMMAND_VFY_PWD, data_package::package_size, data_package::package_string, printFn(), recvPackage(), scanFn(), and sendPackage().
void printFn (uint8_t * str, uint32_t size)
Definition at line 7 of file test.c.
Referenced by main().
void scanFn (uint8_t * str, uint32_t size)
Definition at line 14 of file test.c.
References data_package::package_string.
Referenced by main().
Variable Documentation
data_package txPackage
Definition at line 5 of file test.c.